services:
  misis-stuff:
    container_name: misis-stuff
    build: ./
    restart: always
    env_file:
      - path: ./.env
        required: false
      - path: ./.env.development.local
        required: false
    environment:
      - PORT=8000
